service-registry-discovery:
    build: ./service-registry-discovery
    ports:
     - "8761:8761"
#product-catalog-api:
#    build: ./product-catalog-api
#    ports:
#     - "2222:2222"
#    links:
#     - service-registry-discovery