server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkataravuri/config-repo

eureka:
  instance:
    hostname: 192.168.99.100
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/