# Spring properties
spring:
  application:
     name: product-catalog-api

# Discovery Server Access
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port