apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: e-commerce

configMapGenerator:
  - name: products-configmap
    envs: # using files here as we want to create a whole file
      - .env
generatorOptions:
  disableNameSuffixHash: true # use a static name

resources:
  - service.yaml
  - deployment.yaml
  - namespace.yaml